name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: captainbrosset/github-actions-issue-to-work-item@test-pr-support
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
        with:
          ado_organization: 'microsoft'
          ado_project: 'Edge'
          ado_tags: 'githubSync;patrickTest'
          parent_work_item: 37589346
          ado_area_path: 'Edge\Dev Experience\Developer Tools\F12 Tools'
          ado_dont_check_if_exist: true
          ado_work_item_type: Deliverable